[Setup]
; Application core configuration
AppId={{DEVO-ACCT-1234-5678-90ABCDEF}
AppName=Devo
AppVersion=1.0.0
AppPublisher=Assistant
DefaultDirName={autopf}\Devo
DisableProgramGroupPage=yes
PrivilegesRequired=lowest

; Output installer executable details
OutputDir=Output
OutputBaseFilename=Devo_Setup_v1.0.0
SetupIconFile=assets\devo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
; Supported languages for the installer UI
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
; Task to optionally create a desktop icon during installation
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Include all files and folders generated by PyInstaller
Source: "dist\Devo\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Create shortcuts in the Start Menu and on the Desktop (auto-extracts icon from EXE)
Name: "{autoprograms}\Devo"; Filename: "{app}\Devo.exe"
Name: "{autodesktop}\Devo"; Filename: "{app}\Devo.exe"; Tasks: desktopicon

[Run]
; Launch the application automatically after successful installation
Filename: "{app}\Devo.exe"; Description: "{cm:LaunchProgram,Devo}"; Flags: nowait postinstall skipifsilent